apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
    "type": "host-local",
    "subnet": "10.0.0.0/9",
    "rangeStart": "10.0.0.200",
    "rangeEnd": "10.0.0.216",
    "routes": [
    { "dst": "0.0.0.0/0" }
    ],
    "gateway": "10.0.0.1"
    }
    }'
